name: Metrics

on:
  # Schedule updates (each 8 hour)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  generate_profile:
    runs-on: ubuntu-latest
    steps:
      - name: General
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: general.svg
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community
          config_order: base.header, base.activity+community, languages, habits, rss
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          # Options
          user: TajangSec
          template: classic
          config_timezone: Asia/Shanghai
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_ignored: 'html, css, Jupyter Notebook'
          plugin_languages_details: lines, percentage
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 30
          plugin_languages_aliases: 'RenderScript:Rust'
          commits_authoring: TajangSec, Tajang@qq.com
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          plugin_rss: yes
          plugin_rss_source: https://h4cker.zip/index.xml
          plugin_rss_limit: 4
          config_padding: 0, 8 + 11%
          
          
      - name: Achievements
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          base: ""
          config_timezone: Asia/Shanghai
          plugin_achievements: yes
          plugin_achievements_limit: 8
          config_padding: 0, 8 + 11%
          config_order: achievements
  
      - name: snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            github-snake.svg?palette=github-light
            github-snake-dark.svg?palette=github-dark
            
      - name: deploy snake to gist
        uses: exuanbo/actions-deploy-gist@v1.1.4
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          gist_id: ${{ secrets.GIST }}
          gist_file_name: github-snake.svg
          file_path: github-snake.svg

      - name: deploy dark snake to gist
        uses: exuanbo/actions-deploy-gist@v1.1.4
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          gist_id: ${{ secrets.GIST }}
          gist_file_name: github-snake-dark.svg
          file_path: github-snake-dark.svg
