name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: left
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: TajangSec
          template: classic
          base: header, activity, community
          config_timezone: Asia/Shanghai
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_ignored: 'html, css, Jupyter Notebook'
          plugin_languages_details: lines, percentage
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 30
          plugin_languages_aliases: 'RenderScript:Rust'
          commits_authoring: TajangSec, Tajang@qq.com
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          plugin_rss: yes
          plugin_rss_source: https://h4cker.zip/index.xml
          plugin_rss_limit: 4
          config_padding: 0, 8 + 11%
          config_order: base.header, base.activity+community, languages, habits, rss
      
      - name: right
        uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: TajangSec
          template: classic
          base: ""
          config_timezone: Asia/Shanghai
          plugin_achievements: yes
          plugin_achievements_limit: 8
          config_padding: 0, 8 + 11%
          config_order: achievements, wakatime
